@echo off
echo Cleaning up duplicate migration...
del database\migrations\2026_07_01_150250_create_systems_table.php
echo Running migrations...
call php artisan migrate
echo Generating Filament Resource...
call php artisan make:filament-resource System --generate
echo Setup completed!
